.TH "getsebool" "8" "11 Aug 2004" "dwalsh@redhat.com" "SELinux Command Line documentation"
.SH "NAME"
getsebool \- get SELinux boolean value(s) 

.SH "SYNOPSIS"
.B getsebool
.I "[-a] [boolean]"

.SH "DESCRIPTION"
.B getsebool 
reports the current state of either a particular SELinux boolean or
all SELinux booleans.  The state consists of two values, the active
value and the pending value.  The active value indicates the value
that is presently applied to the policy.  The pending value indicates
the value that will be applied upon the next boolean commit.
Typically, these values will be the same; they only differ when in the
middle of a boolean change transaction.

The setting of boolean values occurs in two stages; first the pending
value is changed, then the booleans are committed, causing their
active values to become their pending values.  This allows a group of
booleans to be changed in a single transaction, by setting all of
their pending values as desired and then committing once.

.SH OPTIONS
.TP
.B \-a
Show all SELinux booleans.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.
The program was written by Tresys Technology.


.SH "SEE ALSO"
.BR setsebool"(8)", booleans"(8)"
