.TH "selinuxenabled" "1" "7 April 2004" "dwalsh@redhat.com" "SELinux Command Line documentation"
.SH "NAME"
selinuxenabled \- tool to be used within shell scripts to determine if selinux is enabled
.SH "SYNOPSIS"
.B selinuxenabled
.br
Command exits with status 0 if selinux is enabled -256 if it is not enabled.

.SH "DESCRIPTION"
.B selinuxenabled
Indicates whether SELinux is enabled or disabled.

.SH AUTHOR	
	Dan Walsh, <dwalsh@redhat.com>

.SH "SEE ALSO"
.BR setenforce"(8)", getenforce"(8)"
