.TH "setsebool" "8" "11 Aug 2004" "dwalsh@redhat.com" "SELinux Command Line documentation"
.SH "NAME"
setsebool \- set SELinux boolean value

.SH "SYNOPSIS"
.B setsebool
.I "boolean value"

.SH "DESCRIPTION"
.B setsebool 
sets the current state of a particular SELinux boolean to a given value.
The value may be 1 or true to enable the boolean, or 0 or false to disable it.
Only the current boolean value is affected; the boot-time default settings
defined by /etc/selinux/SELINUXTYPE/booleans are not changed by this utility.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.
The program was written by Tresys Technology.


.SH "SEE ALSO"
.BR getsebool"(8)", booleans"(8)"
