include ../../Makeconfig

all:
	cd extattr && $(MAKE) all
	cd extattrctl && $(MAKE) all

install:
	cd extattr && $(MAKE) install
	cd extattrctl && $(MAKE) install

clean:
	cd extattr && $(MAKE) clean
	cd extattrctl && $(MAKE) clean
