all:
	cd save_trace && gnumake
	cd sec_trace && gnumake

clean:
	cd save_trace && gnumake clean
	cd sec_trace && gnumake clean

install:
	cd save_trace && gnumake install
	cd sec_trace && gnumake install
