all:
	cd sedarwin && gnumake
	cd libsepol/src && gnumake
	cd libselinux && gnumake
	cd programs && gnumake
	cd policy && gnumake

clean:
	cd sedarwin && gnumake clean
	cd libsepol/src && gnumake clean
	cd libselinux && gnumake clean
	cd programs && gnumake clean
	cd policy && gnumake clean

install:
	cd sedarwin && gnumake install
	cd libsepol/src && gnumake install
	cd libselinux && gnumake install
	cd programs && gnumake install
	cd policy && gnumake install
