.TH "getcon" "3" "1 January 2004" "russell@coker.com.au" "SE Linux API documentation"
.SH "NAME"
getcon, getprevcon, getpidcon \- get SE Linux security context of a process.
.SH "SYNOPSIS"
.B #include <selinux/selinux.h>
.sp
.BI "int getcon(security_context_t *" context );
.br 
.BI "int getprevcon(security_context_t *" context );
.br
.BI "int getpidcon(pid_t pid, security_context_t *" context );

.SH "DESCRIPTION"
.B getcon
retrieves the context of the current process, which must be free'd with
freecon.

.B getprevcon
same as getcon but gets the context before the last exec.

.B getpidcon
returns the process context for the specified PID.

.SH "RETURN VALUE"
On error -1 is returned.  On success 0 is returned.

.SH "SEE ALSO"
.BR freecon "(3), " setexeccon "(3)"
