POLICY=		test
POLICY_VER=	1.0
POLICY_COMPVER=	1.0
POLICY_DESC=	"Framework error detection policy"
POLICY_SRCS=	mac_test.c
POLICY_NOMAN=	yes

include ../Makeconfig
include $(DARWIN_ROOT)/build/PolicyKext.mk
